export const RECEIVE_FILMS_SUCCESS = 'RECEIVE_FILMS_SUCCESS';
export const RECEIVE_FILMS_PENDING = 'RECEIVE_FILMS_PENDING';
export const RECEIVE_FILMS_ERROR = 'RECEIVE_FILMS_ERROR';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
